# syntax=docker/dockerfile:1
# development dockerfile for nextjs

ARG NODE_VERSION=22.12.0

FROM node:${NODE_VERSION}-alpine AS base

FROM base AS deps

RUN apk add --no-cache libc6-compat

WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i; \
  else echo "Lockfile not found." && exit 1; \
  fi

COPY . .

EXPOSE 3000

CMD [ "npm", "run", "dev" ]